const mongoose = require("mongoose");
const Account = require("../models/AccountModel");
const fs = require("fs");
const path = require("path");

const baseSchema = new mongoose.Schema({
  accountCategories: [{ type: String }],
  taxTypes: [
    {
      taxCode: { type: String, required: true, unique: true },
      tax: { type: String, required: true },
      percentage: { type: Number, required: true },
    },
  ],
  companyTypes: [
    {
      company: { type: String, required: true, unique: true },
    },
  ],
  userTypes: [
    {
      user: { type: String, required: true, unique: true },
      access: [{ type: String }],
    },
  ],
  accessTypes: [
    { code: { type: String, unique: true }, access: { type: String } },
  ],
  paymentMethods: [{ type: String }],
  ReceiptEntryType: [{ type: String }],
  paymentTerms: [{ term: { type: String }, value: { type: Number } }],
  workGroups: [{ type: String }],
  rentalAccrual: { type: mongoose.Schema.Types.Mixed },
  incomeAccounts: [{ type: String }],
  expensesAccounts: [{ type: String }],
  retainedEarningAccount: { type: mongoose.Schema.Types.Mixed }
});

const baseModel = new mongoose.model("Bases", baseSchema);

async function insertDefaultValues() {
  // insert default values here
  console.log("inserting system default........");
  await baseModel.deleteMany();

  const defaultBase = new baseModel({
    accountCategories: [
      "ASSETS",
      "LIABILITIES",
      "CAPITAL",
      "REVENUES/INCOME",
      "EXPENSES",
    ],
    taxTypes: [
      { taxCode: "wpt", tax: "PERCENTAGE TAX", percentage: 0.0 },
      { taxCode: "vat-gov", tax: "Government", percentage: 0.12 },
      { taxCode: "vat-ts", tax: "Taxable Sales", percentage: 0.12 },
      { taxCode: "vat-zr", tax: "Zero-Rated", percentage: 0.0 },
      { taxCode: "vat-es", tax: "Exempt Sales", percentage: 0.0 },
      { taxCode: "vat-cg", tax: "Capital Goods", percentage: 0.12 },
      { taxCode: "vat-g", tax: "Goods", percentage: 0.12 },
      { taxCode: "vat-s", tax: "Service", percentage: 0.12 },
      {
        taxCode: "wtc",
        tax: "INCOME TAX WITHHELD FROM EMPLOYEES",
        percentage: 0.25,
      },
    ],
    companyTypes: [
      { company: "Private" },
      { company: "Public" },
      { company: "Non-Profit" },
      { company: "Government" },
    ],
    userTypes: [
      {
        user: "Administrator",
        access: [
          "br",
          "ca",
          "cs",
          "us",
          "ss",
          "rp",
          "s",
          "as",
          "c",
          "i",
          "e",
          "ps",
          "b",
          "v",
          "en",
          "pn",
          "rn",
          "jn",
          "bm",
          "fd",
          "be",
          "or",
          "orx",
          "fs",
          "dp"
        ],
      },
      {
        user: "Accountant",
        access: [
          "br",
          "ca",
          "ss",
          "rp",
          "b",
          "v",
          "en",
          "pn",
          "rn",
          "jn",
          "bm",
          "fd",
          "be",
          "or",
          "orx",
          "fs"
        ],
      },
      {
        user: "Accountant II",
        access: [
          "br",
          "ca",
          "ss",
          "rp",
          "b",
          "v",
          "en",
          "pn",
          "rn",
          "jn",
          "bm",
          "fd",
          "be",
          "or",
          "fs"
        ],
      },
      {
        user: "Accountant III",
        access: [
          "br",
          "ca",
          "ss",
          "rp",
          "b",
          "v",
          "en",
          "pn",
          "rn",
          "jn",
          "bm",
          "fd",
          "be",
          "or",
          "fs"
        ],
      },
      {
        user: "Accountant IV",
        access: [
          "br",
          "ca",
          "ss",
          "rp",
          "b",
          "v",
          "en",
          "pn",
          "rn",
          "jn",
          "bm",
          "fd",
          "be",
          "or",
          "fs"
        ],
      },
      {
        user: "Accountant V",
        access: [
          "br",
          "ca",
          "ss",
          "rp",
          "b",
          "v",
          "en",
          "pn",
          "rn",
          "jn",
          "bm",
          "fd",
          "be",
          "or",
          "fs"
        ],
      },
      {
        user: "OFFICER-IN-CHARGE",
        access: [
          "br",
          "ca",
          "ss",
          "rp",
          "b",
          "v",
          "en",
          "pn",
          "rn",
          "jn",
          "bm",
          "fd",
          "be",
          "or",
          "fs"
        ],
      },
      {
        user: "OFFICER-IN-CHARGE, FSG",
        access: [
          "br",
          "ca",
          "ss",
          "rp",
          "b",
          "v",
          "en",
          "pn",
          "rn",
          "jn",
          "bm",
          "fd",
          "be",
          "or",
          "fs"
        ],
      },
      {
        user: "OFFICER-IN-CHARGE, FAD",
        access: [
          "ca",
          "ss",
          "rp",
          "b",
          "v",
          "en",
          "pn",
          "rn",
          "jn",
          "bm",
          "fd",
          "be",
          "or",
          "fs"
        ],
      },
      {
        user: "ASSISTANT GENERAL MANAGER",
        access: [
          "ca",
          "cs",
          "us",
          "ss",
          "rp",
          "s",
          "as",
          "c",
          "i",
          "e",
          "ps",
          "b",
          "v",
          "en",
          "pn",
          "rn",
          "jn",
          "bm",
          "fd",
          "be",
          "or",
          "fs"
        ],
      },
      {
        user: "GENERAL MANAGER",
        access: [
          "ca",
          "cs",
          "us",
          "ss",
          "rp",
          "s",
          "as",
          "c",
          "i",
          "e",
          "ps",
          "b",
          "v",
          "en",
          "pn",
          "rn",
          "jn",
          "bm",
          "fd",
          "be",
          "or",
          "fs"
        ],
      },
      {
        user: "OIC-GENERAL MANAGER",
        access: [
          "ca",
          "cs",
          "us",
          "ss",
          "rp",
          "s",
          "as",
          "c",
          "i",
          "e",
          "ps",
          "b",
          "v",
          "en",
          "pn",
          "rn",
          "jn",
          "bm",
          "fd",
          "be",
          "or",
          "fs"
        ],
      },
      {
        user: "DEPARTMENT MANAGER III-LEGAL",
        access: [
          "ca",
          "cs",
          "us",
          "ss",
          "rp",
          "s",
          "as",
          "c",
          "i",
          "e",
          "ps",
          "b",
          "v",
          "en",
          "pn",
          "rn",
          "jn",
          "bm",
          "fd",
          "be",
          "or",
          "fs"
        ],
      },
      {
        user: "TREASURER",
        access: [
          "or"
        ],
      },

    ],
    accessTypes: [
      { code: "ca", access: "Chart of Accounts" },
      { code: "cs", access: "Company Settings" },
      { code: "us", access: "Users Settings" },
      { code: "ss", access: "System Setup" },
      { code: "s", access: "Sales" },
      { code: "as", access: "All Sales" },
      { code: "c", access: "Customers" },
      { code: "i", access: "Invoices" },
      { code: "e", access: "Expenses" },
      { code: "ps", access: "Products & Services" },
      { code: "b", access: "Bills" },
      { code: "v", access: "Vendors" },
      { code: "en", access: "Entries" },
      { code: "pn", access: "Payment Entries" },
      { code: "rn", access: "Receipt Entries" },
      { code: "jn", access: "Journal Entries" },
      { code: "rp", access: "Reports" },
      { code: "bm", access: "Budget Monitoring" },
      { code: "fd", access: "Funds Data Entry" },
      { code: "be", access: "Budget Data Entry" },
      { code: "or", access: "Order of Payment" },
      { code: "orx", access: "Update General Ledger from Order of Payment" },
      { code: "fs", access: "Financial Statements" },
      { code: "br", access: "Bank Reconciliation"},
      { code: "dp", access: "Depreciation"},
      { code: "asm", access: "Asset Management"},

    ],
    // paymentMethods: ["Cash", "Cheque", "Bank Transfer"],
    paymentMethods: ["Cash", "Cheque", "Others"],
    ReceiptEntryType: ["Cash Receipt", "Deposit Slip"],
    paymentTerms: [
      { term: "net15", value: 15 },
      { term: "net30", value: 30 },
      { term: "net60", value: 60 },
    ],
    workGroups: [
      "AMG",
      "Corplan",
      "Corporate",
      "FAD",
      "FMG",
      "Legal",
      "OC",
      "OGM",
      "SPG",
      "BAC",
      "CSG",
      "CCG",
      "Disposal",
      "IAD",
      "IG-BD",
      "DavaoFoodExchangeProject",
      "COA",
      "GAD",
      "NDCISO",
      "PingagProject",
      "BIRInputVAT",
    ],
    // holds information on how to create the rental accrual form
    rentalAccrual: {
      entryType: "Journal",
      particulars: "RENT ACCRUAL",
      accrual: {
        debitTo: { code: "10301010B", name: "RENTAL RECEIVABLE" },
        creditTo: { code: "40202050", name: "RENT/LEASE INCOME" },
      },
      securityDeposit: {
        debitTo: { code: "10301010E", name: "OTHER NON-INCOME REC.-CURRENT" },
        creditTo: { code: "40603990", name: "MISCELLANEOUS INCOME" },
      },
    },
  });
  const t = await defaultBase.save();
  console.log(t);
}

module.exports = {
  insertDefaultValues,
  baseModel,
};
